source 'https://rubygems.org'
gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-sass-converter', '1.5.2'
gem 'webrick'
gem 'tzinfo'
gem 'tzinfo-data'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
